[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["saur0x"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
# clap = "2.33.3"
# image = "0.23.14"
